

INSERT INTO DB_CEIBA_ODONTOLOGIA.ODONTOLOGO(ID_ODONTOLOGO, NOMBRES, APELLIDOS, FECHA_INGRESO, ESTADO) VALUES (1, 'FELIPE', 'FRANCO', PARSEDATETIME('25/08/2020', 'dd/MM/yyyy'), 'S');
--INSERT INTO DB_CEIBA_ODONTOLOGIA.CLIENTE(ID_CLIENTE, NOMBRES, APELLIDOS) VALUES (1, 'LA MOSA', 'LA OTRA');
--insert into db_ceiba_odontologia.detalle_cita(ID_DETALLE_CITA, ID_ODONTOLOGO, ID_CLIENTE, FECHA_CITA, HORA_CITA, VALOR_CITA) values (1, 1, 1, STR_TO_DATE('21,5,2020','%d,%m,%Y'), 3, 35000);