DELETE FROM DB_CEIBA_ODONTOLOGIA.DETALLE_CITA;
DELETE FROM DB_CEIBA_ODONTOLOGIA.ODONTOLOGO;
DELETE FROM DB_CEIBA_ODONTOLOGIA.CLIENTE;
DELETE FROM DB_CEIBA_ODONTOLOGIA.LOGIN;

INSERT INTO DB_CEIBA_ODONTOLOGIA.ODONTOLOGO(ID_ODONTOLOGO, NOMBRES, APELLIDOS, FECHA_INGRESO, ESTADO) VALUES (1, 'FELIPE', 'FRANCO', PARSEDATETIME('25/08/2020', 'dd/MM/yyyy'), 'S');
INSERT INTO DB_CEIBA_ODONTOLOGIA.ODONTOLOGO(ID_ODONTOLOGO, NOMBRES, APELLIDOS, FECHA_INGRESO, ESTADO) VALUES (3, 'FELIPE', 'FRANCO', PARSEDATETIME('25/08/2020', 'dd/MM/yyyy'), 'S');
INSERT INTO DB_CEIBA_ODONTOLOGIA.CLIENTE(ID_CLIENTE, NOMBRES, APELLIDOS) VALUES (1, 'LA MOSA', 'LA OTRA');
INSERT INTO DB_CEIBA_ODONTOLOGIA.CLIENTE(ID_CLIENTE, NOMBRES, APELLIDOS) VALUES (3, 'LA MOSA', 'LA OTRA');
INSERT INTO DB_CEIBA_ODONTOLOGIA.LOGIN(ID_LOGIN, USUARIO, CLAVE) VALUES (1, 'Cliente', 'Prueba');
INSERT INTO DB_CEIBA_ODONTOLOGIA.DETALLE_CITA(ID_DETALLE_CITA, FECHA_CITA, HORA_CITA, VALOR_CITA, ID_ODONTOLOGO, ID_CLIENTE, ID_LOGIN) values (1, PARSEDATETIME('25/08/2020', 'dd/MM/yyyy'), 3, 35000, 1, 3, 1);
INSERT INTO DB_CEIBA_ODONTOLOGIA.DETALLE_CITA(ID_DETALLE_CITA, FECHA_CITA, HORA_CITA, VALOR_CITA, ID_ODONTOLOGO, ID_CLIENTE, ID_LOGIN) values (3, PARSEDATETIME('25/08/2020', 'dd/MM/yyyy'), 3, 35000, 1, 3, 1);
